# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a635a6dd15ca868b3a48747c4a448683fd57e1200440883eea43803f4d14ac19f274e4c3025bc3ef11e019bfdf5b00f128b183a253a831192dc64298e54eedc

test:
  secret_key_base: 154981af02c9ba5508e8280f230610b01ba912a31003ada396a07bc17820c93cec2473891baeaa223b3be41dc768a7f9b1078c6bb1867ec2c8646cd4ee3463d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
